version: '2'
services:
  configserver:
    image: confsvr:chap1
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY:       "IMSYMMETRIC"
  microserhello:
    image: microserhello:chap1
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"